### PR TITLE
Refactor type-declarations

### LINKED ISSUE #117: Version 1.1.0 breaks typescript imports
Hey there,

my gulpfile is written in Typescript and `gulp-replace` is used like this:

```typescript
import replace from "gulp-replace";

function doSomething() {
  return gulp.src("directory/*.html")
    .pipe(replace("string", "anotherString"))
    .pipe(gulp.dest("anotherDirectory"));
}

exports.build = gulp.series(doSomething);
```

After upgrading to `~1.1.0`, this breaks with

```
gulpfile.ts:46:35 - error TS2349: This expression is not callable.
  Type 'typeof import("<somePath>/node_modules/gulp-replace/index")' has no call signatures.
```

I also tried

```typescript
import { replace } from "gulp-replace";
import * as replace from "gulp-replace";
```

but without success 😕 

Any help appreciated!

### PR DESCRIPTION
**Pull request by manuth**
The type-declarations currently shipped with `gulp-replace` are incorrect.

The type-declaration (`index.d.ts`) states, that you have to import `gulp-replace` using a statement like this:
```js
const { replace } = require("gulp-replace");
```

But actually, `gulp-replace` has to be imported as followed:
```js
const replace = require("gulp-replace");
```

Thus, all versions containing this type-declaration (`index.d.ts`) can't be used in TypeScript.
Changes made in this PR solve this issue by adjusting the type-declarations accordingly.
Also, changes made in this PR will add a return-type to the `replace`-function and refactor the js-documentation.

Fixes #117 
Closes #113

### CODE REVIEW

**Comment by manuth** [comment]
And, for further elaboration:

TypeScript's
```ts
export declare function replace() { }
```

Basically is the equivalent of
```js
module.exports.replace = function replace() { };
```

While
```ts
declare function replace() { }
export = replace;
```

is the equivalent of 
```js
module.exports = function replace() { };
```

**Comment by lazd** [comment]
@jon2180 does this PR get it right when compared to #113 ? Thanks!

**Comment by manuth** [comment]
@lazd also, you might want to copy-paste the type-declaration from `DefinitelyTyped` as they also take care of stuff like the `skipBinary`-option

**Comment by manuth** [comment]
@lazd I added all commits of the other PRs to this one.
This here PR contains all changes I've proposed.

**Comment by lazd** [comment]
@manuth excellent!

@jon2180, can you please review this PR and let me know if it's good to merge? Thank you!

**Comment by lazd** [comment]
@y805939188 can you verify that this PR fixes the issue you were addressing in #113?

**Comment by lazd** [comment]
@jon2180 @y805939188 can you please help me review this PR? Thank you!

**Comment by Pustur** [comment]
With the current definition file I get the following error:

`File '/[…]/gulp-replace/index.d.ts' is not a module. ts(2306)`

The error goes away if I add `export = replace;` at the end of `index.d.ts` but I'm not sure that's the best way.

The code that I'm using is taken from #117 

```js
import gulp from 'gulp';
import replace from 'gulp-replace';

function doSomething() {
  return gulp
    .src('directory/*.html')
    .pipe(replace('string', 'anotherString'))
    .pipe(gulp.dest('anotherDirectory'));
}

exports.build = gulp.series(doSomething);
```

Other than that, this PR has my approval.

**Comment by manuth** [comment]
Hello @Pustur
Thanks for having a look at my PR.

Could you please verify whether both
```ts
import * as replace from "gulp-replace";
```
and
```ts
import replace = require("gulp-replace");
```

Work with the definition in my PR?

**Comment by Pustur** [comment]
@manuth Both have the same problem. It says it's not a module.

**Comment by manuth** [comment]
@Pustur did you replace the contents of `index.d.ts` with the one from my PR?
You can find my PR's `index.d.ts` here: https://github.com/lazd/gulp-replace/blob/bd4f34a12de8689e3574870c252f118b95994c9e/index.d.ts

**Comment by manuth** [comment]
Also, in order to test my change correctly, you need to have `@types/node` installed (either as normal dependency or as dev-dependency).

**Comment by manuth** [comment]
> @manuth Both have the same problem. It says it's not a module.

Ooooh - nvm I forgot to add `export = replace;` to my file - thanks for reminding me ✨

**Comment by manuth** [comment]
Alright! My PR's ready
@Pustur thanks a ton!

Could you please verify once more?

**Comment by Pustur** [comment]
Work for me now, thanks @manuth 👍

**Comment by manuth** [comment]
@lazd if you don't mind, I'll add another test to `realworld.js` for sort of testing whether `gulp-replace` can be used as expected.

**Comment by manuth** [comment]
@Pustur I removed a redundant declaration of the replacer-function which you can pass instead of an actual replacement (in commit 19de5fe).
Does that look good to you?

Thanks for your help!
And @lazd thank you very much for your patience! ✨

**Comment by Pustur** [comment]
I just noticed that when using a function, the `this` keyword has `any` type.  
`this.file` should contain a vinyl instance as described in the [readme](https://github.com/lazd/gulp-replace#replacement).

I made a gist with the changes that seem to work for me: https://gist.github.com/Pustur/34f8f2590e25d53fb5ff9a893bb16c19/revisions

Of course you have to add `@types/vinyl` to the devDependencies for this to work.

<details>
<summary>
See screenshot with the changes in vscode
</summary>

</details>

**Comment by manuth** [comment]
@Pustur awesome! Thanks for the input! 😄 
I added your recommended changes right away

**Comment by manuth** [comment]
@Pustur alright! I'm ready to have my PR verified 😄

**Review by Pustur — APPROVED** [review]

**Review by schw4rzlicht — APPROVED** [review]
Works for me (#117) too 👍

**Comment by jon2180** [comment]
@manuth  Hello, I have a question.

 I run gulp successfully with typescript  in my local machine. please check the following environments and scripts at first.

My Environment: 

```
Windows 10 20H2
TypeScript 4.2.3
Node.JS  14.16.0 LTS
Gulp  4.0.2
ts-node 9.1.1 // enable to write `gulpfile` scripts with typescript
```

My Test `package.json` in example project:

```json
{
  "name": "gulp-replace-inplace",
  "description": "An example that shows how to search/replace a file in place",
  "version": "0.0.1",
  "devDependencies": {
    "@types/gulp": "^4.0.8",
    "gulp": "^4.0.2",
    "ts-node": "^9.1.1"
  }
}
```

My Type Definition of `gulp-replace` plugin:

```d.ts
declare function replace(
    search: string | RegExp,
    _replacement: string | (() => string) | ((search: string, ...args: any[]) => string),
    options?: { skipBinary: boolean }
): NodeJS.ReadWriteStream;

// IMPORTANT
export = replace;
```

My Test Gulpfile Script in example project.

```typescript
// gulpfile.ts
// same with the example `inplace`
import gulp from 'gulp';
// IMPORTANT
import replace from '../../index';

function replaceText() {
  // Do an in-place replace on file.txt
  return gulp.src('file.txt', { base: './' }).pipe(replace('roof', 'world')).pipe(gulp.dest('./'));
}

export default replaceText;
```

According to [the official documents of export=](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require), I must use `import replace = require("../../index")` statement to import the plugin.

> Excerpt:\
> When exporting a module using export =, TypeScript-specific import module = require("module") must be used to import the module.

When I run My `gulpfile.ts` script, it should throw an exception but no actually. And I noticed that your code preferred `import module = require('module')`. What`s the difference? It confused me a lot.

Thanks.

**Comment by manuth** [comment]
@jon2180 I understand your confusion and, tbh, that's exactly what I got confused about, too, when hearing about the `import [...] from`, `import * as [...] from` and `import [...] = require`-confusion.

Anyways:
There is an option called `esModuleInterop` and one called `allowSyntheticDefaultImports`.
When having both of them enabled (`allowSyntheticDefaultImports` is enabled automatically if `esModuleInterop` is enabled), you can import both `default`-exports and `export =`-exports using the `import [...] from`-statement.

To me it looks like `gulp` enables `esModuleInterop` automatically.

**Comment by lazd** [comment]
LGTM, thanks for the review everyone!

**Pull request merged**
