### PR TITLE
Add a return-type to the type-declaration

### PR DESCRIPTION
**Pull request by manuth**
Currently, the return-type of the type-declaration is set to `any`.
This PR properly sets the return-type to node's `ReadWriteStream`-type.

Related to #113 and #114

### CODE REVIEW

**Comment by lazd** [comment]
Thanks, @manuth! Can you go ahead and consolidate the rest of the TypeScript related PRs into this PR and I will go ahead and merge/release?

**Comment by lazd** [comment]
Include the documentation changes from #116 as well. Thanks!

**Comment by manuth** [comment]
Alright, will do 😁 (in about 4-5 hours, though)

**Comment by manuth** [comment]
Closed in favor of #114

**Pull request closed without merging**
