### PR TITLE
Use through2 instead of event-stream

### PR DESCRIPTION
**Pull request by shinnn**
* I replaced [event-stream](https://github.com/dominictarr/event-stream) with [through2](https://github.com/rvagg/through2).

  According to [the acceptance test suite for gulp plugins](https://github.com/gulpjs/acceptance), [it is not recommended that a gulp plugin depends on event-stream](https://github.com/gulpjs/acceptance#dependencies).

  > **Reason** Old streams + bloated kitchen sink

  Actually, this plugin doesn't use gazillions of event-stream's methods.
* I replaced [gulp-util](https://github.com/gulpjs/gulp-util) with [vinyl](https://github.com/wearefractal/vinyl). gulp-util will be deprecated. https://github.com/gulpjs/gulp/issues/360

### CODE REVIEW

**Comment by shinnn** [comment]
@lazd What do you think?

**Comment by lazd** [comment]
@shinnn I just took a look at the code and this looks like a huge improvement. Merging!

**Comment by shinnn** [comment]
@lazd Thanks! Could you release a new version?

**Comment by lazd** [comment]
I updated dependencies then changed `package.json` to use exact dependency versions (no `^` as we've been bitten before by bad updates to deps) and released as `gulp-replace@0.5.3`.

Thanks for the contribution!

**Comment by shinnn** [comment]
@lazd 

I know why you lock the dependency versions in this project. https://github.com/bevry/istextorbinary/issues/3 I agree to lock the version of istextorbinary.

However, that is the very rare case, I think. At least the developers of replacestream and through2 are both awesome programmers so we can rely on the versioning of these two projects.

How about using `^` for replacestream and through2?

**Comment by lazd** [comment]
@shinnn I totally understand your point of view and agree that the folks behind those libraries are rockstars, but mistakes can still happen.

Given that `gulp-replace` may be used in thousands of build processes, I'd rather be certain it'll continue to work if left untouched than potentially pick up fixes to dependent libraries. Of course, I'll have to more closely monitor dependency versions, but I think the stability of locking dependency versions outweighs the burden of monitoring whether an update is needed.

**Comment by shinnn** [comment]
@lazd :+1: Also correct.

**Pull request merged**
