### PR TITLE
Add filepath to replacement callback

### PR DESCRIPTION
**Pull request by ianstarz**
This adds access to the file path within the replacement hook for replace operations that are based on conventional directory structures

### CODE REVIEW

**Comment by oleggromov** [comment]
:+1: for this feature, it is useful.

**Comment by lazd** [comment]
This PR does not seem to support regex search and replace for this feature. If you can find a way to support that (using `replace.bind()` maybe?) then I think we can go forward with it, but we need feature parity between normal search/replace and regex for this to go in.

Also, docs and tests please! :)

**Comment by oleggromov** [comment]
Lazd, the replacement function can also be called from within the `replacestream` library call, thus, for consistency, the fix should involve the streamed input too, doesn't it? The problem is in creating inconsistency on the other side: `replacestream` calls the replace function with a different bunch of arguments (just like String.prototype.replace calls its arguments of type function; details can be found in [readme](https://www.npmjs.com/package/replacestream)) while `gulp-replace` is going to introduce its own format.

How do you think should this issue be solved?

**Comment by oleggromov** [comment]
I made a correct and consistent for all use cases fix in a sibling PR: https://github.com/lazd/gulp-replace/pull/67
Please take a look.

**Comment by ianstarz** [comment]
Thanks @oleggromov, closing in favor of #67

**Pull request closed without merging**
